# yaml 配置
version: "3.7"
services:
  mysql0507:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "bubble"
      MYSQL_PASSWORD: "root"
    volumes:
      - ./init.sql:/data/application/init.sql
  redis0500:
    image: "redis:5.0.7"
    ports:
      - "6379:6379"
  bubble_app:
    build: .
    command: sh -c "./wait-for.sh mysql0507:3306 -- ./bubble ./conf/config.ini"
    depends_on:
      - mysql0507
      - redis0500
    ports:
      - "8080:8080"