name: "bluebell"
mode: "dev"
port: 8080
start_time: "2022-01-01"
machine_id: 20

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

auth:
  jwt_expire: 8760
  refresh_expire: 8760

mysql:
  host: "127.0.0.1"
  #默认的mysql方式
  #port: 3306
  #使用docker 中的mysql
  port: mysql0507
  user: "root"
  password: "root"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 100

redis:
  host: "127.0.0.1"
  port: "6379"
  password: ""
  db: 0
  pool_size: 10

